language: node_js
node_js:
  - 12
cache: yarn
install:
  - yarn
script:
  - yarn build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git config --global user.name "ss"
  - git config --global user.email "ss@gmail.com"
  - git add -A
  - git commit -m 'deploy'
  - git push --quiet --force "https://${GH_TOKEN}@${REPO_BRANCH}"
